<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>HoodReplacer.SmokeTest</AssemblyName>
    <RootNamespace>HoodReplacer.SmokeTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HoodReplacer.Engine\HoodReplacer.Engine.csproj" />
  </ItemGroup>
</Project>
